=== VijayEluri/truedolist-java/xsd/todo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="todoItem">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="optional" />
			<xs:attribute name="title" type="xs:string" use="required" />
			<xs:attribute name="href" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="todoList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="todoItem" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="optional" />
			<xs:attribute name="title" type="xs:string" use="required" />
			<xs:attribute name="href" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="todoLists">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="todoList" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
<!-- 	
	<xs:element name="todoListsComplete">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="todoListComplete" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="todoListComplete">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="todoItem" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="title" type="xs:string" use="required" />
			<xs:attribute name="href" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
-->	
</xs:schema>

=== VijayEluri/truedolist-java/xsd/TodoListsSample.xml
<?xml version="1.0" encoding="UTF-8"?>
<todoLists xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="todo.xsd">
	<todoList title="list1" id="1234">
		<todoItem id="2345" title="listitem" />
		<todoItem id="3456" title="listitem2" />
	</todoList>
	<todoList title="list2" id="abcd">
		<todoItem id="4" title="listitem3" />
		<todoItem id="5" title="listitem4" />
	</todoList>
	<todoList title="list3" id="asdf">
		<todoItem id="5" title="listitem5" />
		<todoItem id="6" title="listitem6" />
	</todoList>
</todoLists>
